### ISSUE TITLE
[ADD] parsing logs from journald

### ISSUE THREAD

**Issue by SuperSandro2000** [MrDrache333/snowflake-prometheus-exporter#1]
**Is your feature request related to a problem? Please describe.**
I am not running snowflake through a docker container but a systemd service and it logs to journald.

**Describe the solution you'd like**
Having support for that without switching to Docker.

**Describe alternatives you've considered**
Don't have metrics.

**Additional context**

**Comment by francisco-core** [comment]
I was in the exact same situation. The way I fixed this was to first export from the systemd journal to a file and then call the script on that file:

```bash
sudo journalctl -o cat -u snowflake-proxy > snowflake-logs.txt
python3 main.py snowflake-logs.txt
```
